version: '2'
services:
  rabbitmq:
    image: "rabbitmq:3"
    container_name: "msg"
  mongo:
    image: "mongo:3"
    container_name: "mongo"
    ports: 
       - '27017:27017'
  http-source:
    image: "springcloudstream/http-source-rabbit:1.0.2.RELEASE"
    ports:
      - "9000:8080"
    links:
      - "rabbitmq:msg"
    command: "--spring.cloud.stream.bindings.output.destination=http_raw --spring.rabbitmq.host=msg"
  geocoding-processor:
    image: "komushi/spring-cloud-stream-processor-geocoding-reverse:latest"
    links:
      - "rabbitmq:msg"
      - "mongo"
    command: "--properties.mongo.hostName=mongo --properties.mongo.database=geojson --properties.mongo.collection=blocks --spring.cloud.stream.bindings.input.destination=http_raw --spring.cloud.stream.bindings.input.group=transform_geotuple --spring.cloud.stream.bindings.output.contentType=application/json --spring.cloud.stream.bindings.output.destination=transform_geotuple --spring.rabbitmq.host=msg"
